version: '3.8'

services:
  gmail-cli:
    build: .
    container_name: gmail-cli
    volumes:
      # Mount credentials and token files
      - ./data:/app/data
      # Mount credentials.json if it exists
      - ./credentials.json:/app/credentials.json:ro
      # Mount token.json if it exists
      - ./token.json:/app/token.json
    environment:
      # Set token file location
      - TOKEN_FILE=/app/data/token.json
      - CREDENTIALS_FILE=/app/credentials.json
    # Keep container running for interactive use
    stdin_open: true
    tty: true
    # Override default command to keep container running
    command: tail -f /dev/null
    restart: unless-stopped

  # Alternative service for one-time commands
  gmail-cli-run:
    build: .
    container_name: gmail-cli-run
    volumes:
      - ./data:/app/data
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json
    environment:
      - TOKEN_FILE=/app/data/token.json
      - CREDENTIALS_FILE=/app/credentials.json
    # This service runs commands and exits
    profiles:
      - run
